// React types
export const GET_SETTING = 'GET_SETTING';
export const SET_SETTING = 'SET_SETTING';

export const CLEAR_ACCOUNT_CACHE = 'CLEAR_ACCOUNT_CACHE';
export const CLEAR_PRODUCER_CACHE = 'CLEAR_PRODUCER_CACHE';
export const RESET_ALL_STATES = 'RESET_ALL_STATES';
export const RESET_SYSTEM_STATES = 'RESET_SYSTEM_STATES';
export const RESET_VALIDATION_STATES = 'RESET_VALIDATION_STATES';
export const RESET_INVALID_SETTINGS = 'RESET_INVALID_SETTINGS';

export const SET_TEMPORARY_KEY = 'SET_TEMPORARY_KEY';
export const SET_WALLET_KEY = 'SET_WALLET_KEY';

export const WALLET_LOCK = 'WALLET_LOCK';
export const WALLET_REMOVE = 'WALLET_REMOVE';
export const WALLET_UNLOCK = 'WALLET_UNLOCK';

export const GET_ACCOUNT_REQUEST = 'GET_ACCOUNT_REQUEST';
export const GET_ACCOUNT_SUCCESS = 'GET_ACCOUNT_SUCCESS';
export const GET_ACCOUNT_FAILURE = 'GET_ACCOUNT_FAILURE';
export const GET_ACTIONS_REQUEST = 'GET_ACTIONS_REQUEST';
export const GET_ACTIONS_SUCCESS = 'GET_ACTIONS_SUCCESS';
export const GET_ACTIONS_FAILURE = 'GET_ACTIONS_FAILURE';

export const GET_ACCOUNT_BALANCE_REQUEST = 'GET_ACCOUNT_BALANCE_REQUEST';
export const GET_ACCOUNT_BALANCE_SUCCESS = 'GET_ACCOUNT_BALANCE_SUCCESS';
export const GET_ACCOUNT_BALANCE_FAILURE = 'GET_ACCOUNT_BALANCE_FAILURE';

export const GET_GLOBALS_REQUEST = 'GET_GLOBALS_REQUEST';
export const GET_GLOBALS_SUCCESS = 'GET_GLOBALS_SUCCESS';
export const GET_GLOBALS_FAILURE = 'GET_GLOBALS_FAILURE';

export const GET_PRODUCERS_REQUEST = 'GET_PRODUCERS_REQUEST';
export const GET_PRODUCERS_FAILURE = 'GET_PRODUCERS_FAILURE';
export const GET_PRODUCERS_SUCCESS = 'GET_PRODUCERS_SUCCESS';

export const VALIDATE_ACCOUNT_FAILURE = 'VALIDATE_ACCOUNT_FAILURE';
export const VALIDATE_ACCOUNT_PENDING = 'VALIDATE_ACCOUNT_PENDING';
export const VALIDATE_ACCOUNT_SUCCESS = 'VALIDATE_ACCOUNT_SUCCESS';

export const VALIDATE_KEY_FAILURE = 'VALIDATE_KEY_FAILURE';
export const VALIDATE_KEY_PENDING = 'VALIDATE_KEY_PENDING';
export const VALIDATE_KEY_SUCCESS = 'VALIDATE_KEY_SUCCESS';

export const VALIDATE_NODE_FAILURE = 'VALIDATE_NODE_FAILURE';
export const VALIDATE_NODE_PENDING = 'VALIDATE_NODE_PENDING';
export const VALIDATE_NODE_SUCCESS = 'VALIDATE_NODE_SUCCESS';

export const VALIDATE_WALLET_PASSWORD_FAILURE = 'VALIDATE_WALLET_PASSWORD_FAILURE';
export const VALIDATE_WALLET_PASSWORD_PENDING = 'VALIDATE_WALLET_PASSWORD_PENDING';
export const VALIDATE_WALLET_PASSWORD_SUCCESS = 'VALIDATE_WALLET_PASSWORD_SUCCESS';

export const VALIDATE_STAKE_FAILURE = 'VALIDATE_STAKE_FAILURE';
export const VALIDATE_STAKE_PENDING = 'VALIDATE_STAKE_PENDING';
export const VALIDATE_STAKE_SUCCESS = 'VALIDATE_STAKE_SUCCESS';
export const VALIDATE_STAKE_CONFIRMING = 'VALIDATE_STAKE_CONFIRMING';
export const VALIDATE_STAKE_NULL = 'VALIDATE_STAKE_NULL';

export const STAKE_PENDING = 'STAKE_PENDING';
export const STAKE_SUCCESS = 'STAKE_SUCCESS';
export const STAKE_FAILURE = 'STAKE_FAILURE';

export const GET_CHAIN_INFO_REQUEST = 'GET_CHAIN_INFO_REQUEST';
export const GET_CHAIN_INFO_SUCCESS = 'GET_CHAIN_INFO_SUCCESS';
export const GET_CHAIN_INFO_FAILURE = 'GET_CHAIN_INFO_FAILURE';

export const SYSTEM_DELEGATEBW_PENDING = 'SYSTEM_DELEGATEBW_PENDING';
export const SYSTEM_DELEGATEBW_SUCCESS = 'SYSTEM_DELEGATEBW_SUCCESS';
export const SYSTEM_DELEGATEBW_FAILURE = 'SYSTEM_DELEGATEBW_FAILURE';
export const SYSTEM_DELEGATEBW_NULL = 'SYSTEM_DELEGATEBW_NULL';

export const SYSTEM_UNDELEGATEBW_PENDING = 'SYSTEM_UNDELEGATEBW_PENDING';
export const SYSTEM_UNDELEGATEBW_SUCCESS = 'SYSTEM_UNDELEGATEBW_SUCCESS';
export const SYSTEM_UNDELEGATEBW_FAILURE = 'SYSTEM_UNDELEGATEBW_FAILURE';
export const SYSTEM_UNDELEGATEBW_NULL = 'SYSTEM_UNDELEGATEBW_NULL';

export const SYSTEM_VOTEPRODUCER_FAILURE = 'SYSTEM_VOTEPRODUCER_FAILURE';
export const SYSTEM_VOTEPRODUCER_REQUEST = 'SYSTEM_VOTEPRODUCER_REQUEST';
export const SYSTEM_VOTEPRODUCER_SUCCESS = 'SYSTEM_VOTEPRODUCER_SUCCESS';

export const SYSTEM_REGPRODUCER_PENDING = 'SYSTEM_REGPRODUCER_PENDING';
export const SYSTEM_REGPRODUCER_SUCCESS = 'SYSTEM_REGPRODUCER_SUCCESS';
export const SYSTEM_REGPRODUCER_FAILURE = 'SYSTEM_REGPRODUCER_FAILURE';

export const SYSTEM_TRANSFER_PENDING = 'SYSTEM_TRANSFER_PENDING';
export const SYSTEM_TRANSFER_SUCCESS = 'SYSTEM_TRANSFER_SUCCESS';
export const SYSTEM_TRANSFER_FAILURE = 'SYSTEM_TRANSFER_FAILURE';

export const GET_ACCOUNT_BY_KEY_REQUEST = 'GET_ACCOUNT_BY_KEY_REQUEST';
export const GET_ACCOUNT_BY_KEY_SUCCESS = 'GET_ACCOUNT_BY_KEY_SUCCESS';
export const GET_ACCOUNT_BY_KEY_FAILURE = 'GET_ACCOUNT_BY_KEY_FAILURE';
export const GET_ACCOUNT_BY_KEY_CLEAR = 'GET_ACCOUNT_BY_KEY_CLEAR';
