// React types
export const SET_SETTING = 'SET_SETTING';

export const GET_ACCOUNT_REQUEST = 'GET_ACCOUNT_REQUEST';
export const GET_ACCOUNT_SUCCESS = 'GET_ACCOUNT_SUCCESS';
export const GET_ACCOUNT_FAILURE = 'GET_ACCOUNT_FAILURE';

export const GET_PRODUCERS_REQUEST = 'GET_PRODUCERS_REQUEST';
export const GET_PRODUCERS_FAILURE = 'GET_PRODUCERS_FAILURE';
export const GET_PRODUCERS_SUCCESS = 'GET_PRODUCERS_SUCCESS';
