// React types
export const GET_SETTING = 'GET_SETTING';
export const SET_SETTING = 'SET_SETTING';

export const SET_WALLET_KEY = 'SET_WALLET_KEY';

export const GET_ACCOUNT_REQUEST = 'GET_ACCOUNT_REQUEST';
export const GET_ACCOUNT_SUCCESS = 'GET_ACCOUNT_SUCCESS';
export const GET_ACCOUNT_FAILURE = 'GET_ACCOUNT_FAILURE';

export const GET_GLOBALS_REQUEST = 'GET_GLOBALS_REQUEST';
export const GET_GLOBALS_SUCCESS = 'GET_GLOBALS_SUCCESS';
export const GET_GLOBALS_FAILURE = 'GET_GLOBALS_FAILURE';

export const GET_PRODUCERS_REQUEST = 'GET_PRODUCERS_REQUEST';
export const GET_PRODUCERS_FAILURE = 'GET_PRODUCERS_FAILURE';
export const GET_PRODUCERS_SUCCESS = 'GET_PRODUCERS_SUCCESS';
